### ISSUE TITLE
Data wystawienia faktur

### ISSUE THREAD

**Issue by enzzo-ux** [chilek/lms#2065]
Cześć
Postawiłem nowy serwer + nowy LMS 26.0 .  Dump bazy ze starego (25-git ). Import bazy do nowego. Niby wszystko ok - po za data wystawienia faktur.
Faktury u nas generowane są zawsze 1-go dnia miesiąca przez lms-payments.php.
Po imporcie do nowego LMS`a wszystkie faktury maja date wystawienia na koniec miesiąca czyli powinno być 01.07 jest 30.06
Powinno być 01.06 jest 31.05 itd.. - zrobił się bałagan.
Na starym lms oczywiście poprawnie.
Faktury wystawione "recznie" w trakcie miesiąca mają po imporcie poprawne daty wystawienia.
Jakiś pomysł czemu pozmieniał daty na F-VAT generowanych automatycznie ?

**Comment by chilek** [comment]
Witam, nie rozwiązujemy problemów w wersjach sprzed kilku miesięcy, a jedynie w tych z bieżącego stanu gałęzi master.
Jeśli potrzebujesz poprawek do wersji numerowanych to rozważ użycie LMS+ (obecnie najwyższa seria ma wersję 26.32).
Więcej informacji: https:/llms-plus.org.
Jednak jeśli chcesz pozostać przy LMS to po prostu podnieść swoją instalację do wersji bieżącej z gałęzi **master** i wtedy sprawdź czy problem rozwiązał się.

**Comment by enzzo-ux** [comment]
Wersja jest już najnowsza, problem pozostał. W backupie bazy numeracja jest poprawna, po wczytaniu bazy zmienia się numeracja faktur i data wystawienia. Na starym serv. wystawiona była faktura o nr 1234/07/21 , data wystawienia 01.07.2021, data sprzedaży 01.07.2021
Do nowego zaimportował faktura nr 1234/06/21 , data wystawienia 30.06.2021, data sprzedaży 30.06.2021
na starym faktury generowane były przez: lms-payments.php --fakedate=2021/07/01 o ile to ma jakieś znaczenie i mają poprawną date oraz numer.
Faktura wystawiona na starym serwerze ręcznie w ui 2.07.2021 została zaimportowana z poprawną datą oraz numerem.

**Comment by chilek** [comment]
Sprawdź w php.ini `date.timezone` czy masz `Europe/Warsaw`.

**Comment by enzzo-ux** [comment]
Bingo - serwer świeżynka :) Piwo stawiam :)
