### ISSUE TITLE
Problem z generacją Rejestru sprzedaży oraz jpk-FA Jpk-VAT

### ISSUE THREAD

**Issue by mocakow** [chilek/lms#2081]
Próbując wygenerować  rejest sprzadaży oraz pliki Jpk-fa i jpk-vat
Po 10 minutach generowania jpk-vat nic się nie wygenerowalo to samo z jpk-fa
Rejestr sprzedaży udalo się wygenerować wydłużając sesje do 30 minut. Generacja raportu trwała 27 minut.
Niestety JPK-VAT nie wygenrowal sie. (przy 30 minowej sesji).

swieży git, baza mariadb. DB 2021072600

Z ciekawości cofnołem sie do backupu lms z 22.07 baza DB: 2021072103
Wszystko wyglada ok rejestr sprzedaży się robi JPK-fa i JPK-VAT też.
Niestety coś jest skopane z customerlist pokazuje sumaryczne wartości zadłużenia inne niz faktyczne w samym kliencie. Gdzie są poprawne. 
Tak samo w sumarycznym Administracja/informacje też ilość i suma zadłużenia  jest niepoprawna.

**Comment by mocakow** [comment]
podciagnąłem na razie do git-a z 23.07.2021 DB2021072300 raport i pliki sie generują

**Comment by chilek** [comment]
Próbowałem przed chwilą na środowisku testowym z tysiącem faktur wystawionych w czerwcu 2021. Generowanie zarówno JPK-VAT jak i JPK-FA trwa parę sekund. Platforma to:

- php 7.3,
- postgresql 13.3.

**Comment by mocakow** [comment]
Masz gdzieś jak przejść z tego mysql na postgresa postawilbym szybko baze i popróbowal bo mam pewne zaszłości
Mozesz podac dokladną specyfikacje co to za system itd ? Gdzie znajdę narzędzie do conwersi mysql2postgresql

**Comment by mocakow** [comment]
Udalo mi sie wlaczyć mariadb 10.3 php 7.3 Prawie wszystko działa procz backupów bazy z lms być może ktoś mial taki problem jak coś to dajcie linka Moze brakuje jakiegoś modułu php albo czegos w konfiguracji php.

**Comment by mocakow** [comment]
Problem backupu to byl problem ze strukturą bazy. coś się tam kiedyś musialo nie upnąć. Przy okazji w tanlicy adresses wyciąłem ponad milion duplikatów :) Co zmniejszyło bazę o połowę.
Pozostaje nierozwiazany problem: przy imporcie danych nie zmieniają się wartość pokazywana przez moduł welcome.php
I nie widać wpłat na liście moduł customerlist.php. 
W podglądzie klienta wystko ok.… Na liście wartości sprzed importu płatności do bazy.(wartości pokazywane się nie zmieniają.)

System: 
devuan-beowolf  czyli debian 10 bez systemd
baza mariadb 10.3.29
php wersja  7.3.29

**Comment by mocakow** [comment]
Winny był brak triggerów w bazie..
