### ISSUE TITLE
Lms-payments,  flaga EE i JPK-VAT

### ISSUE THREAD

**Issue by mocakow** [chilek/lms#2096]
Wcześniej domyślnie ustawione było tak, że klient indywidualny z automata miał EE=1. W trakcie testów lms-payments  dla klienta indywidualnego nie jest ustawiana wartość 'EE' = 1 ?
Coś zostało zmienione ? Czy jakis domyślny parametr w ustawieniach zmienił domyślną wartość ?
Czy parametr invoices.force_telecom_service_flag działa ? Ustawiłem na true i 1 i jakoś tak… „nie bardzo”.
Czy z ustawioną flagą - tworząc nową fakturę - nie powinien być domyślnie zazaczony kwadracik „usługa telekomunikacyjna” ?
![screen-2021-08-11-17-25-18](https://user-images.githubusercontent.com/72433169/129057940-e9f1ac2d-6fc9-436a-8314-7ede602d3822.png)

Nowy (wczorajszy) git… php7.3 mariadb 10.5.11.

**Comment by chilek** [comment]
https://www.podatki.gov.pl/jednolity-plik-kontrolny/wyjasnienia/nowe-zasady-wypelniania-jpk-vat-z-deklaracja-jpk_v7m-jpk_v7k/

**Comment by mocakow** [comment]
Jak dla mnie w oznaczeniu EE nic się nie zmienia punkt 3b (w domyśle „nie są płatnikami podatku VAT w rozumieniu ustawy o VAT”) . Ale mogę się mylić, więc rzucilem temat do biura rachunkowego. Będą drążyć. :)

**Comment by chilek** [comment]
Jaką politykę wcześniej stosowałeś, tzn. do 30 VI 2021? Dla większości polityka zmieniła się od 1 lipca 2021.

**Comment by mocakow** [comment]
Wszyscy indywidualni  ee=1. Wysyłane jpk-vat do biura rachunkowego.. 
Lipcowy też posłałem do biura z ee=1 dla indywidualnych. 
Muszą to przetrawić. 
We wtorek myślę, że będę wszystko wiedział (mam nadzieję). Podejrzewam, że na informację podatkową nie ma co dzwonić, bo tam zacytują kawałek z Twojego linka. ;) Gry wprowadzali JPK-VAT tak cytowali… sądzę, że nic się w tym temacie nie zmieniło.
W sumie, to nie jest problem w bazie zmienić flagę na fakturach. 
Jak coś będę wiadział dam znać.

**Comment by mocakow** [comment]
Stan na dziś jest taki aby nie zaznaczać EE do końca roku po nowym roku SW i EE będą mialy jedno oznaczenie.
Choć na niektórych portalach piszą że EE oznaczone  do końca roku (od lipca do grudnia). Jednak skłaniam się do tego co ustalilo biuro rachunkowe „nie oznaczać”.Pewnie co US to inny obyczaj.
 Od stycznia WSTO_EE
