### ISSUE TITLE
Dodanie nowego formatu adresu MAC (aaaa-bbbb-cccc) w widoku komputerów

### ISSUE THREAD

**Issue by interduo** [chilek/lms#2105]
**Czy nowa funkcja jest związana z jakimś problemem? Prosimy opisać.**
Konieczność ręcznego zamieniania kropek na myślniki przy kopiuj/wklej.

**Opisz swoją propozycję rozwiązania**
1. Kolejny format adresu MAC - ten pojawia się na OLTach w konsoli.
2. Reformatowanie adresu MAC po kliknięciu przydałoby się również w widoku urządzeń sieciowych w panelu rozwijanym "Adresy MAC".

**Comment by chilek** [comment]
Było i jest.

**Comment by interduo** [comment]
Nie jest jak mówisz:
1. Jest jedynie podobny format ale ma kropki zamiast myślników.
2. Klikam w module netdevinfo w panelu "Adresy MAC" w adres MAC - format jest bez zmian. 
Patrzyłem nawet debugerem czy jest coś podpięte pod ten element i nie jest.

**Comment by interduo** [comment]
O czyli jednak nie było. Dziękuję :)

A uda się wrzucić to reformatowanie adresów MAC również do zakładki "Adresy MAC" w netdevinfo?
