### ISSUE TITLE
Gotowy template pdf faktury korygującej

### ISSUE THREAD

**Issue by mocakow** [chilek/lms#2108]
Przydałby się template faktury korygującej generujący ją jako pdf. ( dokładnie taki, jak korekta generowana z szablonu invoice.html) Nie korzystam z szablonu FT-0100. (przelew mi nie jest potrzebny)
Faktury i korekty drukowane na zwykłej kartce A4, a generowane jako pdf.

**Comment by interduo** [comment]
Szablon fv jest jednoczesnie szablonem korekty. Widoczność druczka jest sterowana per klient za pomocą zgody lub globalnie za pomocą zmiennej.

**Comment by mocakow** [comment]
Zapytam inaczej: 
Przy ustawieniach:
invoices.cnote_template_file = invoice.html
invoices.template_file = standard
invoices.type = pdf
Generuje mi faktury w pdf, a faktury korygujące w html.
Jak zmusić invoice.html aby faktury korygujące też były generowane jako pdf ?

**Comment by interduo** [comment]
Uzupełnij: invoices.cnote_template_file w najnowszym LMS - domyślnie jest to uzupełnione.
