### ISSUE TITLE
 Brak obsługi błędu ? Adres mac jest już w użyciu.

### ISSUE THREAD

**Issue by mocakow** [chilek/lms#2117]
Od dłuższego czasu wpisując urządzenie sieciowe nie ma informacji że dany mac jest już w użyciu.
Kiedyś była taka informacja przy próbie zapisania maca który był już zapisany w bazie. Efakt jest taki, że naciskając zapisz (np. osprzęt sieciowy) nic się nie dzieje. Można klikakrotnie naciskać „zapisz”, bez skutku. 
Być może, jest to zamierzone działanie (dadana możliwość dopisania do urządzenia wielu adresów mac), ale informacja o adresie mac zapisanym już w systemie  w trakcie zmiany, edycji albo dopisywania urządzenia byłaby wskazana.

**Comment by interduo** [comment]
https://github.com/chilek/lms/commit/0ef6425513b3271cb694374a46e6a8a63b75bc4f to naprawia
