### ISSUE TITLE
[rt] rtnodeadd - lms-ui-advanced-select implementacja

### ISSUE THREAD

**Issue by voytec69** [chilek/lms#2118]
**Czy nowa funkcja jest związana z jakimś problemem? Prosimy opisać.**
Jest rozbieżność w ui pomiędzy dodawaniem/edycją zgłoszenia, a dodawaniem notatki, podczas której jest możliwość zmiany np: kolejki. Bardzo wygodne jest lms-ui-advanced-select, a w rtnodeadd tego brakuje.

**Opisz swoją propozycję rozwiązania**
Uprzejma prośba o implementację lms-ui-advanced-select

**Comment by chilek** [comment]
Poszło również do LMS+ 27 i 26.

**Comment by voytec69** [comment]
Dzięki wielkie ;)

**Comment by voytec69** [comment]
A idąc za ciosem, czy pola Właściciel i Weryfikator też można "zupgrejdować"?
