### ISSUE TITLE
[dziennik transakcji] brak wyświetlania zdarzeń przy zawężeniu okresu do tego samego dnia

### ISSUE THREAD

**Issue by voytec69** [chilek/lms#2124]
Jak w temacie, kiedy określamy datę np od 2021/08/20 do 2021/08/20 to LMS nic nie wyszukuje. Zapewne w przypadku kiedy "od" = "do" to nie dodaje do "do" 23:59:59 sekund. 

Wersja LMS: | 28-git
Wersja LMSDB: | 2021072900
Wersja PostgreSQL: | 13.3
Wersja PHP: | 7.4.21
Wersja Smarty: | 3.1.39

**Comment by chilek** [comment]
Poprawka poszła również do LMS+ 27.x, 26.x, 25.x i 24.x.

**Comment by voytec69** [comment]
Dzięki.
