### ISSUE TITLE
lms-payments.php - nie wystawił opłat na fakturach za połączenia VoIP

### ISSUE THREAD

**Issue by interduo** [chilek/lms#2127]
**Opis błędu**
Skrypt `lms-payments.php` nie naliczył opłat za połączenia głosowe umieszczone w tabeli `voip_cdr`. 
Brak błędów na konsoli przy uruchomieniu skryptu.

**Odtworzenie problemu**
Nie wiem jaki czynnik powoduje problem - proszę o potwierdzenie czy u was się wystawił ten problem.

**Oczekiwane zachowanie**
Na fakturach klientów po uruchomieniu `lms-payments.php` powinny być naliczenia za połączenia voip.

**Środowisko - prosimy o uzupełnienie następującej informacji:**
branch: master (ale na bank dotyczy również najnowszego stable)

**Informacje diagnostyczne**
- [X] Brak błędów w dzienniku zdarzeń bazy danych (dotyczy PostgreSQL). W przypadku błędów prosimy o ich przesłanie.
- [X] Brak błędów w dzienniku zdarzeń serwera www lub daemona php FastCGI (zwykle plik error_log lub ssl_error_log w przypadku Apache/httpd).
- [X] Wykonałem polecenie: `rm -f templates_c/* userpanel/templates_c/*`.
- [X] Wykonałem polecenie: `composer update --no-dev`.

**Comment by interduo** [comment]
@chilek sprawdzisz u siebie?

**Comment by chilek** [comment]
> @chilek sprawdzisz u siebie?

Nie mam na czym, bo w ogóle nie mam rekordów bilingowych :)

**Comment by interduo** [comment]
Dodaj jakikolwiek przypisany do klienta z kosztem 1zł i odpal `lms-payments.php`.

**Comment by interduo** [comment]
@chilek uda Ci się to sprawdzić? Ten problem dotyczy najnowszego stable i mastera.

**Comment by interduo** [comment]
@chilek czy lms-payments.php tworzy Ci się szczątkowe naliczenia dla wszystkich zobowiązań, które mają niepełne okresy rozliczeniowe (np. 01.09.2021 - 17.09.2021) czy dodaje pełne kwoty abonamentu? 

Na fakturze powinno być (ilość dni naliczenia/ilość dni w miesiącu)*kwota abonamentu.
Obecnie generuje się pełna kwota abonamentu.

**Comment by interduo** [comment]
@chilek

Wrzuć do bazy testowej:
```
INSERT INTO public.voipaccounts (id, ownerid, login, passwd, access, creationdate, moddate, creatorid, modid, balance, flags, cost_limit, address_id, description) VALUES ('1', '1', '814753777', 'blank', '0', '1592396162', '0', '1', NULL, '200.00000', '0', NULL, '1', 'DESCRIPTION');

INSERT INTO public.voip_numbers (id, voip_account_id, phone, number_index, tariff_id) VALUES ('1', '1', '814753777', '1', NULL);

INSERT INTO public.voip_cdr (id, caller, callee, call_start_time, totaltime, billedtime, price, status, type, callervoipaccountid, calleevoipaccountid, caller_flags, callee_flags, caller_prefix_group, callee_prefix_group, uniqueid) VALUES ('623228', '814753777', '607893111', '1635721014', '201', '201', '0.50000', '2', '2', '1', NULL, '1', '1', NULL, 'Lokalne', '30f7176a3f3ebeda825f');
```

Uruchom:
`lms-payments.php --fake-date=2021/12/01` 

Oczekujemy:
U klienta ID:1 na fakturze jest pozycja o treści "Połączenia głosowe za okres - 2021/11/01 - 2021/11/31 " 1szt z kosztem 0.50 PLN brutto.

Obecnie:
Jest pusto.

Zbiegło się to z modyfikacjami kodu faktur związanych z możliwością wystawienia faktury jako kwot netto - commit, który wprowadził regres to najprawdopodobniej `e5e71ab504b62f15097ae7e9bc9b32c79ec58fee` lub dwa kolejne modyfikujące plik `bin/lms-payments.php`.

**Comment by chilek** [comment]
W tych zapytaniach powyżej muszę zmienić jedynie ownerid w voipaccounts czy coś jeszcze?

**Comment by chilek** [comment]
Coś mi się wydaje, że jeszcze co najmniej rekord w assignments jest potrzebny, a nie podałeś jego definicji...

**Comment by interduo** [comment]
Koszty są określone w rekordach w tabeli `voip_cdr` w kolumnie `price`.

**Comment by interduo** [comment]
> W tych zapytaniach powyżej muszę zmienić jedynie ownerid w voipaccounts czy coś jeszcze?

Na pustej bazie te INSERTY wchodzą do DB.

**Comment by chilek** [comment]
Czy commit ef7766a3720e6ae63ca902c4efa6215af323dbb4 rozwiązuje Twój problem?

**Comment by interduo** [comment]
W bilingu jest CDR z datą 2.11.2021 odpalam więc `bin/lms-payments.php --fakedate=2021/12/01` po wcześniejszej aktualizacji instancji. Nadal na fakturze nie ma dodatkowej pozycji za połączenia głosowe.

**Comment by interduo** [comment]
Próbowałem dodatkowo utworzyć zobowiązanie z `typ=telefon` ale to również nie pomaga.

**Comment by interduo** [comment]
@chilek uda się coś z tym zrobić?

**Comment by chilek** [comment]
Uda się jak postarasz się bardziej przygotowują solidnie dane do testu.

**Comment by interduo** [comment]
@chilek dałem Ci wrzut działający na czystej bazie danych. Co mogę zrobić więcej?

**Comment by interduo** [comment]
Ok już rozwaliłem - to co brakowało w zrzucie to przypisanie numeru do zobowiązania telefonicznego.

Także commit https://github.com/chilek/lms/commit/ef7766a3720e6ae63ca902c4efa6215af323dbb4 rozwiązuje problem zgłoszenia.
