### ISSUE TITLE
[netadd] przy dodawaniu nowej sieci wymaga dodania hosta

### ISSUE THREAD

**Issue by voytec69** [chilek/lms#2134]
**Wstępna weryfikacja**
Zanim zgłosisz błąd spróbuj najpierw go samodzielnie rozwiązać wspomagając się artykułem
z [naszego wiki](https://github.com/chilek/lms-plus/wiki/faq#problem-z-funkcjonowaniem-aplikacji-lms-plus).

**Opis błędu**
Przy dodawaniu nowej sieci IP do systemu, krzyczy o wybór hosta. 

**Odtworzenie problemu**
Wchodzimy w sieci-> nowa sieć. Uzupełniamy pola nazwa sieci - jakaś sieć , adres sieci - x.x.x.y,  prefix  /24. Reszta pól zostaje defaultowa. Przynajmniej u mnie pole HOST świeci na czerwono i nic tam nie można wybrać bo i w sumie co :)

**Oczekiwane zachowanie**
Ma pozwolić na dodanie sieci bez hosta w przypadku kiedy to nie jest podsieć kliencka, wydzielona z innej sieci. 

Wersja LMS: | 28-git
-- | --
Wersja LMSDB: | 2021082800
Wersja PostgreSQL: | 13.3
Wersja PHP: | 7.4.21
Wersja Smarty: | 3.1.39
LMSSmsCenterPluginDB: | -

**Comment by chilek** [comment]
> Ma pozwolić na dodanie sieci bez hosta w przypadku kiedy to nie jest podsieć kliencka, wydzielona z innej sieci.

Na pewno nie pójdziemy w tę stronę.
