### ISSUE TITLE
[RT] Usuwanie jedynej kategorii

### ISSUE THREAD

**Issue by interduo** [chilek/lms#2147]
**Opis błędu**
Brak możliwości usunięcia jedynej kategorii.

**Odtworzenie problemu**
Kroki odtwarzające błędne zachowanie:
1. Ustaw zmienną `phpui.helpdesk_allow_empty_categories = true`
2. Utwórz ticket i dodaj jedną kategorię.
3. Edytuj ticket - usuń jedyną kategorie.

**Oczekiwane zachowanie**
Możliwość usunięcia kategorii.

**Informacje diagnostyczne**
`[Fri Sep 17 17:36:33 2021] PHP Warning:  explode() expects parameter 2 to be string, array given in /var/www/html/elemesik/lib/LMSManagers/LMSHelpdeskManager.php on line 1722`

**Comment by chilek** [comment]
Te wszystkie błędy to efekt Twojej optymalzacji, gdzie kilka razy pytałem, czy wszystko sprawdziłeś. Nibdy znasz komeny `grep`, `gawk` i `sed`, a jednak nie potrafisz ich używać...

**Comment by interduo** [comment]
Nie bardzo wiem jak mógłbym testować sedem. Robiłem testy manualne tylko dla każdego z pól. Może coś podpowiesz?

**Comment by interduo** [comment]
Łatka pomaga

**Comment by chilek** [comment]
> Robiłem testy manualne dla każdego z pól - tylko na instancji testowej nie miałem włączonej zmiennej.
> Pewnie dlatego to przegapiłem. Nie bardzo wiem jak mógłbym testować sedem/awk. Może coś podpowiesz?

Tu w tej kwestii raczej na Twój dyletantyzm niewiele poradzimy - być może w przyszłości będzie z tym coraz lepiej.
Propozycja jest taka, żeby pewnie inwazyjne zmiany były testowane po prostu u Ciebie lokalnie przez np. 2 tygodnie i co  jakiś czas, żebyś przesyłał nam PR-a ze swojej gałęzi przeznaczonej do włączania takich zmian - najlepiej jak gałąź ta będzie zawsze w stanie takim, że będzie miała tyle pojedynczych commitów ile łatwych do wyróżnienia zmian logicznych (nie ma sensu, żebyśmy widzieli jak w swojej gałęzi zmieniałeś kod źródłowy literka po llterce). Popatrz jak to robią duzi - np. gałąź Linux utrzymywania przez Linusa Torvaldsa (skoro ci duzi tak robią, tzn. że lepiej się nie da, choć pewnie idealnie nie jest). Wiesz dobrze, że ja nie mogę dla jednego PR wybrać w prosty sposób jak złączyć lub przesunąć pojedyczne commit do trochę zagregowanych, a zresztą szkoda nawet na to czasu, skoro możesz przygotować elegancko udokumentowany PR z kilkoma commitami).

**Comment by interduo** [comment]
> Propozycja jest taka, żeby pewnie inwazyjne zmiany były testowane po prostu u Ciebie lokalnie przez np. 2 tygodnie i co jakiś czas, żebyś przesyłał nam PR-a ze swojej gałęzi przeznaczonej do włączania takich zmian - najlepiej jak gałąź ta będzie zawsze w stanie takim, że będzie miała tyle pojedynczych commitów ile łatwych do wyróżnienia zmian logicznych 

Robię tak już okazjonalnie np. https://github.com/chilek/lms/pull/2129.

> (nie ma sensu, żebyśmy widzieli jak w swojej gałęzi zmieniałeś kod źródłowy literka po llterce).

Jestem w trakcie stawiania sobie lokalnego travisa tak, że będzie z tym o wiele lepiej.

**Comment by chilek** [comment]
Rozważ też na poważnie to co napisałem, żebyśmy robili podobnie jak tzw. "duzi".
