### ISSUE TITLE
Aktualizacja z 26->27

### ISSUE THREAD

**Issue by jakrzy** [chilek/lms#2153]
Ubuntu 20.04.3 LTS  + mysql
LMS 26-git, aktualizacja do ver 27.
Strona powitalna LMS, przed zalogowaniem;
Zapytanie: SELECT vd.*, (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) AS label FROM vdivisions vd WHERE 1=1 AND vd.status = 0 ORDER BY (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) asc
Błąd: Table 'lms.vdivisions' doesn't exist

Po zalogowaniu, klienci->lista;
Zapytanie: SELECT vd.*, (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) AS label, vd.id as divisionid FROM vdivisions vd JOIN userdivisions ud ON vd.id = ud.divisionid WHERE 1=1 AND vd.status = 0 AND ud.userid = 1 ORDER BY (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) asc
Błąd: Table 'lms.vdivisions' doesn't exist
Zapytanie: SELECT vd.*, (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) AS label, vd.id as divisionid FROM vdivisions vd JOIN userdivisions ud ON vd.id = ud.divisionid WHERE 1=1 AND ud.userid = 1 ORDER BY (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) asc
Błąd: Table 'lms.vdivisions' doesn't exist
Zapytanie: SELECT c.id AS id, c.lastname, c.name, CONCAT(UPPER(lastname), ' ', c.name) AS customername, c.karma, c.type, c.deleted, status, full_address, post_full_address, c.address, c.zip, c.city, countryid, countries.name AS country, cc.email, ccp.phone, ten, ssn, c.info AS info, extid, message, c.divisionid, c.paytime AS paytime, COALESCE(b.balance, 0) AS balance, COALESCE(t.value, 0) AS tariffvalue, s.account, s.warncount, s.online, (CASE WHEN s.account = s.acsum THEN 1 WHEN s.acsum > 0 THEN 2 ELSE 0 END) AS nodeac, (CASE WHEN s.warncount = s.warnsum THEN 1 WHEN s.warnsum > 0 THEN 2 ELSE 0 END) AS nodewarn FROM customerview c LEFT JOIN (SELECT customerid, (GROUP_CONCAT(contact SEPARATOR ',')) AS email FROM customercontacts WHERE (type & 8 > 0) GROUP BY customerid) cc ON cc.customerid = c.id LEFT JOIN (SELECT customerid, (GROUP_CONCAT(contact SEPARATOR ',')) AS phone FROM customercontacts WHERE (type & 5 > 0) GROUP BY customerid) ccp ON ccp.customerid = c.id LEFT JOIN countries ON (c.countryid = countries.id) LEFT JOIN customerbalances b ON b.customerid = c.id LEFT JOIN ( SELECT a.customerid, SUM( ( CASE a.suspended WHEN 0 THEN (((100 - a.pdiscount) * (CASE WHEN t.value IS null THEN l.value ELSE t.value END) / 100) - a.vdiscount) ELSE ((((100 - a.pdiscount) * (CASE WHEN t.value IS null THEN l.value ELSE t.value END) / 100) - a.vdiscount) * 0 / 100) END ) * ( CASE WHEN a.period <> 0 AND t.period > 0 AND t.period <> a.period THEN ( CASE t.period WHEN 5 THEN 1/12.0 WHEN 7 THEN 1/6.0 WHEN 4 THEN 1/3.0 ELSE 1 END ) ELSE ( CASE a.period WHEN 5 THEN 1/12.0 WHEN 7 THEN 1/6.0 WHEN 4 THEN 1/3.0 WHEN 2 THEN 4.0 WHEN 1 THEN 30.0 ELSE 1 END ) END ) * a.count ) AS value FROM assignments a LEFT JOIN tariffs t ON (t.id = a.tariffid) LEFT JOIN liabilities l ON (l.id = a.liabilityid AND a.period <> 0) WHERE a.commited = 1 AND a.datefrom <= UNIX_TIMESTAMP() AND (a.dateto > UNIX_TIMESTAMP() OR a.dateto = 0) GROUP BY a.customerid ) t ON (t.customerid = c.id) LEFT JOIN (SELECT ownerid, SUM(access) AS acsum, COUNT(access) AS account, SUM(warning) AS warnsum, COUNT(warning) AS warncount, (CASE WHEN MAX(lastonline) > UNIX_TIMESTAMP() - 600 THEN 1 ELSE 0 END) AS online FROM nodes WHERE ownerid > 0 AND ipaddr <> 0 GROUP BY ownerid ) s ON (s.ownerid = c.id) WHERE 1 = 1 ORDER BY c.id desc, c.id ASC LIMIT 100 OFFSET 0
Błąd: Unknown column 'c.karma' in 'field list'
Zapytanie: SELECT vd.*, (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) AS label, vd.id as divisionid FROM vdivisions vd JOIN userdivisions ud ON vd.id = ud.divisionid WHERE 1=1 AND ud.userid = 1 ORDER BY (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) asc
Błąd: Table 'lms.vdivisions' doesn't exist

klienci->nowa grupa;
Zapytanie: SELECT vd.*, (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) AS label, vd.id as divisionid FROM vdivisions vd JOIN userdivisions ud ON vd.id = ud.divisionid WHERE 1=1 AND vd.status = 0 AND ud.userid = 1 ORDER BY (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) asc
Błąd: Table 'lms.vdivisions' doesn't exist
Zapytanie: SELECT vd.*, (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) AS label, vd.id as divisionid FROM vdivisions vd JOIN userdivisions ud ON vd.id = ud.divisionid WHERE 1=1 AND ud.userid = 1 ORDER BY (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) asc
Błąd: Table 'lms.vdivisions' doesn't exist

klienci->polaczenia;
Zapytanie: SELECT vd.*, (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) AS label, vd.id as divisionid FROM vdivisions vd JOIN userdivisions ud ON vd.id = ud.divisionid WHERE 1=1 AND vd.status = 0 AND ud.userid = 1 ORDER BY (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) asc
Błąd: Table 'lms.vdivisions' doesn't exist
Zapytanie: SELECT vd.*, (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) AS label, vd.id as divisionid FROM vdivisions vd JOIN userdivisions ud ON vd.id = ud.divisionid WHERE 1=1 AND ud.userid = 1 ORDER BY (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) asc
Błąd: Table 'lms.vdivisions' doesn't exist
Zapytanie: SELECT COUNT(c.*) FROM customercalls c LEFT JOIN vusers u ON u.id = c.userid
Błąd: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '*) FROM customercalls c LEFT JOIN vusers u ON u.id = c.userid' at line 1

komputery->szukaj;
Zapytanie: SELECT vd.*, (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) AS label, vd.id as divisionid FROM vdivisions vd JOIN userdivisions ud ON vd.id = ud.divisionid WHERE 1=1 AND vd.status = 0 AND ud.userid = 1 ORDER BY (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) asc
Błąd: Table 'lms.vdivisions' doesn't exist
Zapytanie: SELECT vd.*, (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) AS label, vd.id as divisionid FROM vdivisions vd JOIN userdivisions ud ON vd.id = ud.divisionid WHERE 1=1 AND ud.userid = 1 ORDER BY (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) asc
Błąd: Table 'lms.vdivisions' doesn't exist

finanse->lista platnosci;
Zapytanie: SELECT vd.*, (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) AS label, vd.id as divisionid FROM vdivisions vd JOIN userdivisions ud ON vd.id = ud.divisionid WHERE 1=1 AND vd.status = 0 AND ud.userid = 1 ORDER BY (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) asc
Błąd: Table 'lms.vdivisions' doesn't exist
Zapytanie: SELECT vd.*, (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) AS label, vd.id as divisionid FROM vdivisions vd JOIN userdivisions ud ON vd.id = ud.divisionid WHERE 1=1 AND ud.userid = 1 ORDER BY (CASE WHEN vd.label IS NULL THEN vd.shortname ELSE vd.label END) asc
Błąd: Table 'lms.vdivisions' doesn't exist

itp.....
Błąd: Table 'lms.vdivisions' doesn't exist

**Comment by interduo** [comment]
Przebuduj sobie widoki:

DROP VIEW ...
CREATE VIEW ...

Znajdź kod w lms.psql lub lms.mysql

**Comment by jakrzy** [comment]
podczas tworzenia widoku;

Błąd
Zapytanie SQL: Dokumentacja
CREATE VIEW vdivisions AS
    SELECT d.*,
        a.country_id as countryid, a.ccode, a.zip as zip, a.city as city, a.address,
        (CASE WHEN d.firstname IS NOT NULL AND d.lastname IS NOT NULL AND d.birthdate IS NOT NULL THEN 1 ELSE 0 END) AS naturalperson
    FROM divisions d
        JOIN vaddresses a ON a.id = d.address_id

MySQL zwrócił komunikat: Dokumentacja
#1054 - Nieznana kolumna 'd.firstname' w  field list

**Comment by interduo** [comment]
Przejdź na postgresa. Na postgresie kod jest intensywniej testowany ponieważ to jst zalecany silnik db.

**Comment by interduo** [comment]
Ten manual jest nierozwijany od wielu lat.
Jak chcesz mieć aktualną dokumentacje to dołącz do projektu LMSplus.

**Comment by interduo** [comment]
@jakrzy skrypt do konwersji bazy MySQL->PostgreSQL dostępny w LMSplus - możesz użyć również pg_loadera pod warunkiem że sprawdzisz potem strukturę skonwertowanej bazy.
