### ISSUE TITLE
[USERPANEL] Przeglądanie zarchiwizowanych faktur powoduje błędy w httpd

### ISSUE THREAD

**Issue by interduo** [chilek/lms#2161]
**Opis błędu**
Przeglądanie zarchiwizowanych faktur powoduje błędy w httpd

**Odtworzenie problemu**
Kroki odtwarzające błędne zachowanie:
1. Przejdź do panelu abonenckiego
2. Podejrzyj dowolną zarchiwizowaną fakturę w `/?m=finances`
3. Zobacz w log httpd

**Oczekiwane zachowanie**
Brak błędu.

https://github.com/interduo/lms/blob/master/userpanel/modules/finances/invoice.php#L220

`grep 'public function Close' /var/www/html/lms/userpanel/lib/Session.class.php` daje pusty wynik

`[Thu Oct 07 11:18:11.654528 2021] [php7:error] [pid 39364] [client 172.20.2.42:37154] PHP Fatal error:  Uncaught Error: Call to undefined method Session::close() in /var/www/html/lms/userpanel/modules/finances/invoice.php:220\nStack trace:\n#0 /var/www/html/lms/userpanel/modules/finances/functions.php(151): include()\n#1 /var/www/html/lms/userpanel/index.php(288): module_invoice()\n#2 {main}\n  thrown in /var/www/html/lms/userpanel/modules/finances/invoice.php on line 220, referer: https://ebok.interduo.pl/?m=finances`

branch: master, stable

**Comment by interduo** [comment]
W stable ten problem nie występuje u Ciebie?

**Comment by chilek** [comment]
Dlaczego pytasz? Zauważ, że poprawka poszła do wszystkich stable-ów z LMS+.
