### ISSUE TITLE
Configlist: sortowanie numeryczne zamiast alfabetyczne w kolumnie "wartość"

### ISSUE THREAD

**Issue by interduo** [chilek/lms#2169]
**Opisz swoją propozycję rozwiązania**
![Zrzut ekranu z 2021-10-17 18-37-43](https://user-images.githubusercontent.com/17087236/137686710-04083d26-bdad-44a5-9fe2-9f5ecf731d9a.png)

Po włączeniu sortowania kolumny "wartość" (za pomocą kliknięcia w nagłówek kolumny):

Obecnie:
dane w kolumnie "wartość" są sortowane alfabetycznie

Sytuacja oczekiwana:
oznaczyć kolumnę sortowaną numerycznie jakąś dodatkową klasą CSS i wtedy dane w kolumnie "wartość" posortować numerycznie

**Miejsce występowania**
Zła metoda sortowania jest również w kolumnach "Przychód" oraz "Rozchód" w widoku klienta w zakładce "Konto klienta".

![Zrzut ekranu z 2021-10-18 11-05-13](https://user-images.githubusercontent.com/17087236/137701925-ce011474-16b5-4db6-802a-33680006a327.png)

**Comment by chilek** [comment]
> Zła metoda sortowania jest również w kolumnach "Przychód" oraz "Rozchód" w widoku klienta w zakładce "Konto klienta".

A to akurat powinno być realizowalne - jako ćwiczenie poszukaj w jaki sposób w datatables nadawać komórkom wagę przy sortowaniu komórek z kolumny. Poszukałem za Ciebie jak by to można zrobić i zobacz:

https://datatables.net/examples/advanced_init/html5-data-attributes.html

(wystarczyło odpowiednio google zapytać, żeby znaleźć link do tego artykułu :)).

**Comment by interduo** [comment]
Miejsc jest więcej podałem dwa przykładowe.

**Comment by chilek** [comment]
> Jak rozkminię jak działa wrzucanie plików do LMS za pomocą {fileuploads to się wezmę i za to.

Nie widzę związku między jednym i drugim.

**Comment by interduo** [comment]
To już zrobione.
