### ISSUE TITLE
[invoices] zmiana nazwy firmy, a druczek przelewu

### ISSUE THREAD

**Issue by voytec69** [chilek/lms#2194]
Case, 
Zmieniamy nazwę firmy (forma). Robiąc wydruk faktury wystawionej przed zmianą (lub jej podgląd), to widzimy, że na druczku przelewu widnieje już nowa nazwa po zmianie. 
Oczekiwane zachowanie: wystawca na fakturze i nazwa odbiorcy powinna być taka sama.

**Comment by chilek** [comment]
> Oczekiwane zachowanie: wystawca na fakturze i nazwa odbiorcy powinna być taka sama.

Zakładam, że chodzi o wystawcę i nabywcę?

**Comment by voytec69** [comment]
Przepraszam, autokorekta, chodzi o sprzedawcę w górnej części dokumentu i nazwa odbiorcy w dolnej w której znajduje się druczek przelewu. Zmieniamy nazwę nie klienta, a operatora. ;)

**Comment by chilek** [comment]
Czyli obecnie po zmianie danych firmy/oddziału na druczku przelewu zmienia się wyłącznie nazwa firmy (wystawcy)?

**Comment by voytec69** [comment]
W moim przypadku zmieniam tylko nazwę firmy (i to ona zmienia się druczku), nie zmieniałem danych adresowych, to musiałbyś zerknąć skąd są tam brane dane.

**Comment by chilek** [comment]
Prośba o test.

**Comment by voytec69** [comment]
Wyglada na to, ze jest ok ;)

**Comment by voytec69** [comment]
Dzięki.
