### ISSUE TITLE
szybkoszukajka: wyszukiwanie "imię nazwisko" nie znajduje klienta

### ISSUE THREAD

**Issue by interduo** [chilek/lms#2236]
**Opis błędu**
W innych systemach dość często imię podawane jest wcześniej niż nazwisko. 
Wklejając dane z zewnętrznego systemu do szybkoszukajki `qs[customer]` zawsze generowane są puste wyniki wyszukiwania.

**Oczekiwane zachowanie**
Podczas szukania nie bierzmy pod uwagę kolejności wyszukiwanych danych.

Postgres, branch: master/stable

**Comment by mocakow** [comment]
To nie bład. Czy nie jesteś aby… zbyt wygodny ? :)

**Comment by chilek** [comment]
To jest chyba na tyle proste, że zamiast robić zgłoszenie powinieneś poradzić sobie w parę chwili i parę wierszy kodu :)

**Comment by interduo** [comment]
> To jest chyba na tyle proste, że zamiast robić zgłoszenie powinieneś poradzić sobie w parę chwili i parę wierszy kodu :)

Mimo wszystko wolę jednak, żeby było na to zgłoszenie. Bo w nim jest kontekst motywacyjny.

@chilek tak swoją drogą jest jakiś powód, że w wielu miejscach jest:
`$DB->Concat('lastname', "' '", 'c.name')` zamiast skorzystać z widoku `customerview`?

**Comment by chilek** [comment]
Zasadnicza różnica między customerview i customers jest taka, że widok bierze dodatkowe rzeczy związane z nadanymi dostępami do danych klientów. Obejrzyj sobie definicje widoków.

**Comment by chilek** [comment]
> Mimo wszystko wolę jednak, żeby było na to zgłoszenie - bo w nim jest kontekst motywacyjny i wolę posłuchać uwag co do pomysłu przed rozpoczęciem kodowania zamiast dopiero przy PR.

Można to tak nazywać, choć ta to nazywam marnowaniem czasu i potencjału na zbędną biurokrację. Tym bardziej że chodzi o banalne rzeczy.

**Comment by interduo** [comment]
Czy jest sens wyświetlać klientów do których nie mamy dostępu w wynikach wyszukiwania?
A jeśli jest tak to czy nie warto podmienić ikonki na "fa-ban" jeśli do zasobu nie mamy dostępu (i ewentualnie usunąć link)?
