### ISSUE TITLE
[balanceadd] przekierowuje na "biała stronę"

### ISSUE THREAD

**Issue by voytec69** [chilek/lms#2243]
Po dodaniu ręcznie wpłaty przy pomocy formularza na karcie klienta i kliknięciu zapisz - przekierowuje na biała stronę. 
Wpis do bazy dodaje się poprawnie (widać ręcznie wprowadzoną wpłatę). W logach nie widzę nic niepokojącego.

**Comment by chilek** [comment]
Z tej "kategorii" pewnie będzie więcej błędów, bo jesteśmy po serii bardzo inwazyjnych zmian w zakresie obsługi historii adresów po których wędrujemy.
