### ISSUE TITLE
Numer działki w lokalizacjach klienta

### ISSUE THREAD

**Issue by interduo** [chilek/lms#2251]
**Czy nowa funkcja jest związana z jakimś problemem? Prosimy opisać.**
Zdarza się, że podłączany budynek nie ma jeszcze nadanego numeru.  
Wpisywanie tego numeru w numer budynku powoduje nieprawidłowości w raportowaniu.
Wpisywanie tego numeru w pole ulica również nie zda egzaminu bo skrypt lms-teryt.php nadpisze tą wartość.

**Opisz swoją propozycję rozwiązania**
Dodanie pola nr działki w lokalizacjach z wartością niewymaganą.

**Comment by chilek** [comment]
Ostatnio poszły poprawki do raportowania UKE/SIIS polegające na tym, że jeśli nie wpiszemy budynku w adresie, a za to wpiszemy wsp. GPS, to ulica i numer budynku w raporcie pozostaną puste, a wsp. GPS spełnią swoją rolę.
Wpisywać numery działek można by chociażby w i tak rzadko używanym polu nazwa w adresie.

**Comment by interduo** [comment]
U klientów, którzy mają jeden adres rejestrowy nie ma pola "Nazwa".

**Comment by interduo** [comment]
Myślę, że warto, żebyś popatrzył na to pole łaskawym okiem i zobaczył jakie daje również możliwości dla innych nietechnicznych osób.

Pole nazwa przydaje sie już na dokumentach dlatego nie pakowałbym tam nr działki żeby nie psuć tej funkcji.
