### ISSUE TITLE
[netdevadd] wymiana kontrolek na lms-ui-advanced-select

### ISSUE THREAD

**Issue by voytec69** [chilek/lms#2268]
Prośba o zmianę kontrolek na lms-ui-advanced-select dla pól Węzeł sieciowy, projekt inwestycyjny, producent, model.

Dzięki z góry.

**Comment by chilek** [comment]
Producent model nie zmienimy, bo stracilibyśmy możliwość wpisania spoza zdefiniowanych - dlatego te pola to comboboksy.

**Comment by interduo** [comment]
Na liście urządzeń sieciowych to gra rolę?

**Comment by chilek** [comment]
> Na liście urządzeń sieciowych to gra rolę?

A tu znowu nie na temat? :)

**Comment by chilek** [comment]
Kontynuując:
1. Wybór projektu jest również comboboksem - pozwala wpisać wartośc spoza listy - dzięki temu nie trzeba ręcznie tworzyć nowego priojektu.
2. Wybór węzła był i jest lms-ui-advanced-select.
