### ISSUE TITLE
[rtparser] zapętlenie spowodowane zwrotką od serwera pocztowego odbiorcy

### ISSUE THREAD

**Issue by interduo** [chilek/lms#2270]
**Opis błędu**
Mieliśmy po raz kolejny sytuację w której na adres skrzynki podpiętej do parsera dostaliśmy zwrotkę z maila jednego z użytkowników LMS, który miał włączone powiadomienia kolejek. Spowodowało to utworzenie kolejnego ticketu i wysłania kolejnej mailowej z powiadomieniem na ten mail.

Treść maila:
```
Your message to <[mail@domena.pl](mailto:mail@domena.pl)> was automatically rejected:
Quota exceeded (mailbox for user is full)
Reporting-MTA: dns; poczta.domena.pl
Final-Recipient: rfc822; [mail@domena.pl](mailto:mail@domena.pl)
Action: failed
Status: 5.2.2
```

Sytuacja potem poszła wykładniczo i co minutę mieliśmy tworzonych co raz więcej ticketów do momentu czasu ręcznego zatrzymania skryptu lms-rtparser.php. 

Opisywana sytuacja, która się zdarzyła dotyczyła akurat wewnętrznego użytkownika ale mogła by również dotyczyć klienta ponieważ parser odpowiada na przyjmowane zgłoszenia zgodnie z definicją kolejki.

**Oczekiwane zachowanie**
Sytuacja w której skrzynka może się przepełnić jest normalna.
Są też inne sytuacje w których dostaniemy zwrotkę od serwera nadawcy (np. nadawca może mieć np. słaby autoresponder bez limitu odpowiadający na każdego maila lub parser systemów informatycznych klienta również bez takiego zabezpieczenia).

Jak najlepiej okodować parser by był odporny na takie sytuacje?

**Comment by chilek** [comment]
Myślę, że warto by było, żebyś przeanalizował parę różnych zwrotek i znalazł wspólne ich cechy, a następnie, albo dodał kawałek kodu do skryptu, albo opisał dokładnie te cechy.

**Comment by chilek** [comment]
Na feedbacki bym tu nie liczył, bo większość ludzi jest na urlopach, albo pracuje i nie ma czasu na bicie piany :-)

**Comment by interduo** [comment]
Proponuję zmiany:
1. Nie zaczytujmy maili, które zawierają nazwę hosta instancji LMS w `Message-ID`
2. Nie zaczytujmy maili, które mają w `Return-Path: <MAILER-DAEMON>`
3. Nie zaczytujmy wiadomości, które spełniają założenia:
https://github.com/jpmckinney/multi_mail/wiki/Detecting-autoresponders

Będzie ok?

**Comment by chilek** [comment]
Odświeżam wątek - wystapił identyczny problem w jednej z firm, którym świadczymy usługi wsparcia indywidualnego.
Komplet nagłówków wygląda następująco:

```
Return-Path: <>
Delivered-To: bok@myfiber.pl
Received: from h26.seohost.pl
	by h26.seohost.pl with LMTP
	id cMHPOm+1FWNP2zgAX7WgVQ
	(envelope-from <>)
	for <bok@myfiber.pl>; Mon, 05 Sep 2022 10:38:07 +0200
Return-path: <>
Envelope-to: bok@myfiber.pl
Delivery-date: Mon, 05 Sep 2022 10:38:07 +0200
Received: from mail by h26.seohost.pl with local (Exim 4.96)
	id 1oV7cN-00Fgaf-37
	for bok@myfiber.pl;
	Mon, 05 Sep 2022 10:38:07 +0200
X-Failed-Recipients: root@h26.seohost.pl
Auto-Submitted: auto-replied
From: Mail Delivery System <Mailer-Daemon@h26.seohost.pl>
To: bok@myfiber.pl
References: <VAQM2lBYnylx5PFT28dRUk00HSjXoipzaAr7p0ng0@myfiber.pl> <E1oV7Wa-00FaRw-2z@h26.seohost.pl> <confirm.12587.6.1662366782@rtsystem.lmsplus.bestconnect.pl> <E1oV7XX-00FbSd-0Z@h26.seohost.pl> <confirm.12588.6.1662366842@rtsystem.lmsplus.bestconnect.pl> <E1oV7YW-00FcYN-2O@h26.seohost.pl> <confirm.12589.6.1662366903@rtsystem.lmsplus.bestconnect.pl> <E1oV7ZV-00FdgN-1L@h26.seohost.pl> <confirm.12590.6.1662366962@rtsystem.lmsplus.bestconnect.pl> <E1oV7aT-00Fef3-0P@h26.seohost.pl> <confirm.12592.6.1662367022@rtsystem.lmsplus.bestconnect.pl> <E1oV7bQ-00Ffac-01@h26.seohost.pl> <confirm.12594.6.1662367082@rtsystem.lmsplus.bestconnect.pl>
Content-Type: multipart/report; report-type=delivery-status; boundary=1662367087-eximdsn-889316758
MIME-Version: 1.0
Subject: Mail delivery failed: returning message to sender
Message-Id: <E1oV7cN-00Fgaf-37@h26.seohost.pl>
Date: Mon, 05 Sep 2022 10:38:07 +0200

```

Czy czasem `Return-Path` z pustą wartością nie jest od razu wyznaczaniem, ze przetwarzanie posta w helpdesk nie ma sensu?

**Comment by chilek** [comment]
Zacznijmy od tego:

`Many MTAs set Return-Path: <> or Return-Path: <MAILER-DAEMON>, including Microsoft IIS' SMTP service (in most cases, this would signify a bounce)`

Czuję, że to większość zwrotek wytnie (o ile nie wszystkie).

**Comment by chilek** [comment]
Co ma się stać ze zignorowanym postem? Poddany tym samym zasadom, co inne posty przetworzone pozytywnie? Chyba tak.

**Comment by interduo** [comment]
> Co ma się stać ze zignorowanym postem? Poddany tym samym zasadom, co inne posty przetworzone pozytywnie? Chyba tak.

Tak - bo i tak pierwszy trafi do helpdesku.

**Comment by interduo** [comment]
> Zacznijmy od tego:
> 
> `Many MTAs set Return-Path: <> or Return-Path: <MAILER-DAEMON>, including Microsoft IIS' SMTP service (in most cases, this would signify a bounce)`
> 
> Czuję, że to większość zwrotek wytnie (o ile nie wszystkie).

Ja bym dorzucił do tego to co w RFC czyli obecność w nagłówku `Auto-Submitted`

**Comment by chilek** [comment]
> Ja bym dorzucił do tego to co w RFC czyli obecność w nagłówku `Auto-Submitted`.

Tak właśnie zrobiłem i testuję.

**Comment by chilek** [comment]
Testuję następującą zmianę:

```diff
--- a/bin/lms-rtparser.php
+++ b/bin/lms-rtparser.php
@@ -359,6 +359,34 @@ while (isset($buffer) || ($postid !== false && $postid !== null)) {
         $partdata = mailparse_msg_get_part_data($part);
         $headers = $partdata['headers'];
 
+        if (isset($headers['return-path'])) {
+            if (is_array($headers['return-path'])) {
+                $return_paths = $headers['return-path'];
+            } else {
+                $return_paths = array($return_paths);
+            }
+            $return_paths = array_filter($return_paths, function($var) {
+                return $var == '<>' || strtolower($var) == '<mailer-daemon>';
+            });
+            if (!empty($return_paths) || isset($headers['auto-submitted']) && $headers['auto-submitted'] == 'auto-replied') {
+                mailparse_msg_free($mail);
+
+                if ($postid !== false && $postid !== null) {
+                    if ($rtparser_use_seen_flag) {
+                        imap_setflag_full($ih, $postid, "\\Seen");
+                    } else {
+                        imap_clearflag_full($ih, $postid, "\\Seen");
+                    }
+
+                    $postid = next($posts);
+                }
+
+                unset($buffer);
+
+                continue;
+            }
+        }
+
         $mh_from = iconv_mime_decode($headers['from']);
         $mh_to = iconv_mime_decode($headers['to']);
         $mh_cc = isset($headers['cc']) ? iconv_mime_decode($headers['cc']) : '';
```

**Comment by chilek** [comment]
Chyba można zamknąć sprawę. U naszego klienta problem został rozwiązany.

**Comment by interduo** [comment]
Nasz przypadek również. Thx za naprawę.
