### ISSUE TITLE
[teryt]

### ISSUE THREAD

**Issue by Xanshara** [chilek/lms#2280]
root@srv-lms:/var/www/html/lms# lms-teryt.php -f -l 18
lms-teryt.php
(C) 2001-2019 LMS Developers
Using file /etc/lms/lms.ini as config.
Downloading TERYT files...
PHP Deprecated:  Function strftime() is deprecated in /usr/sbin/lms-teryt.php on line 505
PHP Deprecated:  Function strftime() is deprecated in /usr/sbin/lms-teryt.php on line 444
PHP Deprecated:  Function strftime() is deprecated in /usr/sbin/lms-teryt.php on line 444
PHP Deprecated:  Function strftime() is deprecated in /usr/sbin/lms-teryt.php on line 444
PHP Deprecated:  Function strftime() is deprecated in /usr/sbin/lms-teryt.php on line 444
PHP Deprecated:  Function strftime() is deprecated in /usr/sbin/lms-teryt.php on line 444
PHP Deprecated:  Function strftime() is deprecated in /usr/sbin/lms-teryt.php on line 444
PHP Deprecated:  Function strftime() is deprecated in /usr/sbin/lms-teryt.php on line 444
PHP Deprecated:  Function strftime() is deprecated in /usr/sbin/lms-teryt.php on line 444
PHP Deprecated:  Function strftime() is deprecated in /usr/sbin/lms-teryt.php on line 444
Error: Downloaded files: 0. Three expected.

Debian 11.

**Comment by chilek** [comment]
Wystarczy zaktualizować instalacje.
