### ISSUE TITLE
Problem z wydrukiem faktur

### ISSUE THREAD

**Issue by mocakow** [chilek/lms#2281]
Przy próbie  wydruku faktur z Raporty/Faktury (generuje pdf) pojawia się bład.

![screen-2022-07-01-22-28-35](https://user-images.githubusercontent.com/72433169/176964697-ada493f1-10a1-496d-9a24-72ce90e0d215.jpg)

Pojedyńcze faktury z Finanse/Lista faktur da się drukować.

Po podmiance /lib/tcpdf.php z dnia poprzedniego czyli 30.06.2022 sprzed zmian:
Finanse lista faktur drukuje poprawnie kopia + orginał 
Z Raporty/Faktury przy zaznaczonym wydruku orginału i kopii generuje tylko pojedyńczo… czyli oryginał. 
Przy okazji:
W Raporty/Rejestr sprzedaży  Na liście nie pokazuje się Pesel przy odznaczonym  Ukryj pesel klienta. 
LMS:
![screen-2022-07-01-23-17-01](https://user-images.githubusercontent.com/72433169/176971577-98250fa0-0a96-4f61-83b5-5ddf88fc287f.jpg)

**Comment by chilek** [comment]
Dość dawno poprawione.
