### ISSUE TITLE
Karta klienta - brak wartości "Salda przeterminowanego"

### ISSUE THREAD

**Issue by interduo** [chilek/lms#2283]
**Czy nowa funkcja jest związana z jakimś problemem? Prosimy opisać.**
Obecnie trzeba zaglądać do faktur by sprawdzić - ile obecnie realnie zalega klient. Czasami przy fakturach z wydłużonym terminem płatności trzeba się cofać o kilka faktur wstecz - co zjada czas.

**Opisz swoją propozycję rozwiązania**
Proponuję coś takiego jak na widoku:
![Zrzut ekranu z 2022-07-06 12-28-55](https://user-images.githubusercontent.com/17087236/177534049-f88413cf-f521-4bc4-92ee-24e1f4bafb86.png)

**Comment by chilek** [comment]
## pupui.show_customer_due_balance

**Typ:** Wartość logiczna.

**Wartość domyślna:** _false_

**Opis:** Ustawienie na wartość _true_ powoduje prezentację salda wymagalnego w kartotece klienta.

**Dostępność:** od 28.0

## pupui.show_customer_expired_balance

Patrz **[phpui.show_customer_due_balance](#phpuishow_customer_due_balance)**

**Comment by interduo** [comment]
Świetnie, dziękuję w imieniu naszego BOK. A domyślnie nie lepiej włączyć?

**Comment by chilek** [comment]
> Świetnie, dziękuję w imieniu naszego BOK. A domyślnie nie lepiej włączyć?

Nie, bo akurat to niepotrzebnie wprowadza błąd i powoduje dezorientację.
