### ISSUE TITLE
[nodeedit] linktype | linkradiosector | linkspeed | linktechnology

### ISSUE THREAD

**Issue by voytec69** [chilek/lms#2286]
Wersja git - master.

Problem:
Przy edycji komputera, nie ładują się zapisane w bazie dane do pól <option> formularza nodeedit. Zapisuje się poprawnie.

**Comment by chilek** [comment]
Sprawdziłem na formularzu:
https://demo.lms.org.pl/?m=nodeedit&id=71

i jest ok. Nic nie zmieniałem.

**Comment by voytec69** [comment]
A zmień Urządzenie sieciowe na --brak urządzenia-- i zobacz.
