### ISSUE TITLE
ostrzeżenia  w eventadd.php

### ISSUE THREAD

**Issue by chilek** [chilek/lms#2322]
Bieżąca wersja 28-git z master.

Mamy w logu php:
```
PHP Warning:  Undefined variable $search in /var/www/html/lms/modules/eventadd.php on line 55
```

Pojawiło się po ostatnich zmianach związanych z przypisaniem węzłów i urządzeń do zdarzeń terminarza.
Rzuciłem okiem na skrypt php - wygląda, że użycie $search nie przystaje do jego użycia. Czyżby wynikało to ze zmiany
kolejności wierszy kodu?

**Comment by interduo** [comment]
Pewnie zaraz update robię.

**Comment by interduo** [comment]
PHP 8.x pewnie?

**Comment by interduo** [comment]
Proszę: https://github.com/chilek/lms/pull/2323

**Comment by chilek** [comment]
To, co przygotowałem to naprawia jakiś jeden specyficzny przebieg kodu, ale nie rozwiązuję pierwotnego problemu po zmianie koolejności wierszy w kodzie. Hint: szuka frazy `$search` - zobaczysz, że występuje w przypadkowej kolejności, a to znaczy, że trafia do wywołania korzystającego z tego nie wszystko, co trzeba przekazując.

**Comment by interduo** [comment]
Właśnie przez jakiś taki PHP Warning dodałem test `!empty()`. Używasz na produkcji już PHP8.0 czy to jakaś testowa instancja o której piszesz?

**Comment by interduo** [comment]
Przeniosłem to wyżej, żeby nie wykonywać dwa razy tej samej metody - wyczyściłem ten warunek ponieważ nie jest on potrzebny i przy okazji znalazłem kilka drobnych usprawnień, które można wprowadzić w kod.
