### ISSUE TITLE
Zapytania bazy danych GUS REGON - brak obsługi błędów

### ISSUE THREAD

**Issue by interduo** [chilek/lms#2328]
**Czy nowa funkcja jest związana z jakimś problemem? Prosimy opisać.**
Ostatnio usługi API rządowe ładnie powiem "nie zawsze odpowiadają". Obecnie pobierając dane w formularzu dodawania nowego klienta nie wiemy czy po kliknięciu dane nie zostały znalezione czy po prostu nastąpił błąd w komunikacji.

**Opisz swoją propozycję rozwiązania**
W przypadku braku odpowiedzi (po np. 2 sec) popup z komunikatem: "Błąd komunikacji z GUS".
W przypadku "pustej" odpowiedzi np. dla nieistniejącego lub niepoprawnego NIPu, popup z komunikatem: "Brak danych w GUS".

**Alternatywne rozwiązanie**
Podmiana ikonki przycisku pobierz z GUS na czerwony "X" w przypadku błędu komunikacji.
Zielona "fajka" na przycisku w przypadku poprawnie pobranych danych.

**Comment by chilek** [comment]
To już było i nadal jest - w przypadku jakichkolwiek błędów wyświetla się alert z errorem.
