### ISSUE TITLE
problem z autosugestią quicksearch

### ISSUE THREAD

**Issue by piotrek121-cmd** [chilek/lms#2439]
Pierwszy raz korzystam z lms plus i jak instalacja oraz konfiguracja przebiegła bezproblemowo, męczę się z dodaniem autosugestii do pola szybkiego wyszukiwania. Nie wiem czy w jakimś pliku konfiguracyjnym jest to opcja tylko do włączenia czy może jakaś dodatkowa paczka do pobrania? Nie wiem gdzie mogę tego szukać i proszę o pomoc. @chilek @interduo

**Comment by interduo** [comment]
Nie rozumiem co chcesz dodać, gdzie i na czym polega problem.

**Comment by piotrek121-cmd** [comment]
Może pokaże to na screenach. 
![Zrzut ekranu 2024-01-18 075724](https://github.com/chilek/lms/assets/64897434/9c43d239-8faa-4ccb-83de-25bc3f5cf2f0)
to efekt jaki chce uzyskać a to jaki mam obecnie. 
![Zrzut ekranu 2024-01-18 075900](https://github.com/chilek/lms/assets/64897434/12efe610-d56c-443c-88cd-81012caa9a93)
Po prostu lista rozwijana z podpowiedziami klientów się nie uruchamia. I wiem że odpowiada za to skrypt autosuggest.js który jest w pliku jednak nie wiem czemu nie działa. Czy trzeba zinstalować jakiś moduł? Coś zmienić w jakimś pliku konfiguracyjnym? Czy może powinno to działać a przy instalacji coś zepsułem. Dzięki za pomoc. @interduo

**Comment by interduo** [comment]
Mi to działa. Obczaj sobie czy po komendzie `composer update --no-dev` Ci ruszy.

**Comment by interduo** [comment]
Skoro masz abonament z wsparciem lmsplus to zgłaszaj problemy tam: https://github.com/chilek/lms-plus/issues 
Tam jest fajna formatka danych, które musisz dostarczyć zgłaszając błąd - na pewno te dane pozwolą rozwiązać problem.

**Comment by piotrek121-cmd** [comment]
Okej już to zrobię dzięki za pomoc.
